### ISSUE TITLE
GameSceneでロウソクのOn/Offを実装する

### ISSUE THREAD

**Issue by Kasugai0083** [Kasugai0083/Team_A_Production#1]
11/8（金）に向けてGameScene内でロウソクのOn/Off機能を実装する。
それに合わせて、ロウソクの状態によって描画を変更するようにする。

タスク一覧

- [x] ロウソクの情報をまとめたCandleクラスを作成

- [x]  Candleにbool型のステータスを付与

- [x] プレイヤーにマウス情報を付与

- [x] プレイヤーからCandleの情報を取得してステータスを変更できるようにする

- [x] Candleのステータスに依存して描画する

New!
- [x] 作成したCandleコードのリファクタリングを行う

**Comment by Kasugai0083** [comment]
・Candleクラスを作成

`class Candle : public Item {
public:

	Candle() :
		m_HasCenterCaLight(false),
		m_HasRightCaLight(false),
		m_HasLeftCaLight(false)
	{}

	void Init(object::ObjectId id_)override{
		switch (id_) {
		case object::CANDLE_BIG:
			LoadTexture("Res/Game/Item/Candle_Center_Right_Left.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleBigTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleBigTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = CANDLE_BIG_POS;
			m_Size = CANDLE_BIG_SIZE;
			break;
		case object::CANDLE_SMALL:
			LoadTexture("Res/Game/Item/Candle_Center.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleSmallTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleSmallTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = CANDLE_SMALL_POS;
			m_Size = CANDLE_SMALL_SIZE;
			break;
		case object::CANDLE_STAND:
			LoadTexture("Res/Game/Item/Candle_Stand.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleStandTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleStandTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = CANDLE_STAND_POS;
			m_Size = CANDLE_STAND_SIZE;
			break;
		case object::CANDLE_EFFECT:
			LoadTexture("Res/Game/Item/Candle_Right_Effect.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleEffectTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleEffectTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = CANDLE_EFFECT_POS;
			m_Size = CANDLE_EFFECT_SIZE;
			break;
		}
	}

	void Init(object::ObjectId id_, Vec2 pos_) override {
		switch (id_) {
		case object::CANDLE_BIG:
			LoadTexture("Res/Game/Item/Candle_Center_Right_Left.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleBigTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleBigTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = pos_;
			m_Size = CANDLE_BIG_SIZE;
			break;
		case object::CANDLE_SMALL:
			LoadTexture("Res/Game/Item/Candle_Center.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleSmallTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleSmallTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = pos_;
			m_Size = CANDLE_SMALL_SIZE;
			break;
		case object::CANDLE_STAND:
			LoadTexture("Res/Game/Item/Candle_Stand.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleStandTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleStandTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = pos_;
			m_Size = CANDLE_STAND_SIZE;
			break;
		case object::CANDLE_EFFECT:
			LoadTexture("Res/Game/Item/Candle_Right_Effect.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleEffectTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleEffectTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = pos_;
			m_Size = CANDLE_EFFECT_SIZE;
			break;
		}
	}

private:
	
	bool m_HasCenterCaLight;
	bool m_HasRightCaLight;
	bool m_HasLeftCaLight;

};`

**Comment by Kasugai0083** [comment]
・Candleクラスを作成
・Candleにbool型のステータスを付与

```
class Candle : public Item {
public:

	Candle() :
		m_HasCenterCaLight(false),
		m_HasRightCaLight(false),
		m_HasLeftCaLight(false)
	{}

	void Init(object::ObjectId id_)override{
		switch (id_) {
		case object::CANDLE_BIG:
			LoadTexture("Res/Game/Item/Candle_Center_Right_Left.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleBigTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleBigTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = CANDLE_BIG_POS;
			m_Size = CANDLE_BIG_SIZE;
			break;
		case object::CANDLE_SMALL:
			LoadTexture("Res/Game/Item/Candle_Center.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleSmallTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleSmallTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = CANDLE_SMALL_POS;
			m_Size = CANDLE_SMALL_SIZE;
			break;
		case object::CANDLE_STAND:
			LoadTexture("Res/Game/Item/Candle_Stand.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleStandTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleStandTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = CANDLE_STAND_POS;
			m_Size = CANDLE_STAND_SIZE;
			break;
		case object::CANDLE_EFFECT:
			LoadTexture("Res/Game/Item/Candle_Right_Effect.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleEffectTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleEffectTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = CANDLE_EFFECT_POS;
			m_Size = CANDLE_EFFECT_SIZE;
			break;
		}
	}

	void Init(object::ObjectId id_, Vec2 pos_) override {
		switch (id_) {
		case object::CANDLE_BIG:
			LoadTexture("Res/Game/Item/Candle_Center_Right_Left.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleBigTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleBigTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = pos_;
			m_Size = CANDLE_BIG_SIZE;
			break;
		case object::CANDLE_SMALL:
			LoadTexture("Res/Game/Item/Candle_Center.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleSmallTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleSmallTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = pos_;
			m_Size = CANDLE_SMALL_SIZE;
			break;
		case object::CANDLE_STAND:
			LoadTexture("Res/Game/Item/Candle_Stand.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleStandTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleStandTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = pos_;
			m_Size = CANDLE_STAND_SIZE;
			break;
		case object::CANDLE_EFFECT:
			LoadTexture("Res/Game/Item/Candle_Right_Effect.png", TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleEffectTex);
			m_pTex = GetTexture(TEXTURE_CATEGORY_GAME, GameCategoryTextureList::GameCandleEffectTex);

			if (m_pTex == nullptr) {
				return;
			}

			m_Pos = pos_;
			m_Size = CANDLE_EFFECT_SIZE;
			break;
		}
	}

private:
	
	bool m_HasCenterCaLight;
	bool m_HasRightCaLight;
	bool m_HasLeftCaLight;

};
```

**Comment by Kasugai0083** [comment]
それに伴い、ObjectManagerクラスに追記

```
void ObjectManager::Init() {
	for (int i = 0; i < object::MAX_OBJECT_NUM; i++) {
		m_pObjects[i]->Init();
	}

	m_pObjects[object::CANDLE_BIG]->Init(object::CANDLE_BIG);
	m_pObjects[object::CANDLE_SMALL]->Init(object::CANDLE_SMALL);
	m_pObjects[object::CANDLE_EFFECT]->Init(object::CANDLE_EFFECT);
	m_pObjects[object::CANDLE_STAND]->Init(object::CANDLE_STAND);

}

void ObjectManager::Init(object::ObjectId id_, Vec2 pos_) {

	m_pObjects[id_]->Init(pos_);
	m_pObjects[id_]->Init(id_, pos_);

}
```
ObjectManager::Init()の追記分が特に怪しい
というより、Managerクラスの旨味を阻害している印象を受ける

**Comment by Kasugai0083** [comment]
・プレイヤーにマウス情報を付与
プレイヤーはキャラクターマネージャーで動作しているので、
必要な時にマウス座標を取りづらい
廃案にする

**Comment by Kasugai0083** [comment]
・プレイヤーからCandleの情報を取得してステータスを変更できるようにする
→キャンドルアップデートからステータスを変更する

```
	void Update()override {

		if (HasRectangleHit(GetMousePos().X, GetMousePos().Y, m_Pos.X, m_Pos.Y, (m_Pos.X + m_Size.Width), (m_Pos.Y + m_Size.Height)) == true) {
			m_OnMouse = true;
			if (OnMouseDown(Left) == true) {
				switch (PepshiMan()->CurrentViewID()) 
				{
					case GameData::CENTER:
						if (m_HasCenterCaLight == false) {
							m_HasCenterCaLight = true;
						}
						else {
							m_HasCenterCaLight = false;
						}
					break;
					case GameData::RIGHT:
						if (m_HasRightCaLight == false) {
							m_HasRightCaLight = true;
						}
						else {
							m_HasRightCaLight = false;
						}
					break;
					case GameData::LEFT:
						if (m_HasLeftCaLight == false) {
							m_HasLeftCaLight = true;
						}
						else {
							m_HasLeftCaLight = false;
						}				
						break;
				}
			}
		}
		else {
			m_OnMouse = false;
		}

	}

	bool HasCenterCaLight()override{
		return m_HasCenterCaLight;
	}
	bool HasRightCaLight()override{
		return m_HasRightCaLight;
	}
	bool HasLeftCaLight()override{
		return m_HasLeftCaLight;
	}
```

→オブジェクトマネージャーからロウソクの情報を取得できるように追加
```
bool ObjectManager::HasCaLight(GameData::SubGameScene sce_) {
	switch (sce_)
	{
	case GameData::CENTER:
		return m_pObjects[object::CANDLE_BIG]->HasCenterCaLight();
		break;
	case GameData::LEFT:
		return m_pObjects[object::CANDLE_SMALL]->HasLeftCaLight();
		break;
	case GameData::RIGHT:
		return m_pObjects[object::CANDLE_SMALL]->HasRightCaLight();
		break;
	default:
		break;
	}
}

```

**Comment by Kasugai0083** [comment]
@yttmwork 
現在、作成中のIssueです

**Comment by Kasugai0083** [comment]
当たり判定がCenter,Right,Leftで重複しているため、
クリックで上手く動かない様子

```
	void Update()override {

		if (HasRectangleHit(GetMousePos().X, GetMousePos().Y, m_Pos.X, m_Pos.Y, (m_Pos.X + m_Size.Width), (m_Pos.Y + m_Size.Height)) == true) {
			m_OnMouse = true;
			if (OnMouseDown(Left) == true) {
				switch (PepshiMan()->CurrentViewID()) 
				{
					case GameData::CENTER:
						if (m_HasCenterCaLight == false) {
							m_HasCenterCaLight = true;
						}
						else {
							m_HasCenterCaLight = false;
						}
					break;
					case GameData::RIGHT:
						if (m_HasRightCaLight == false) {
							m_HasRightCaLight = true;
						}
						else {
							m_HasRightCaLight = false;
						}
					break;
					case GameData::LEFT:
						if (m_HasLeftCaLight == false) {
							m_HasLeftCaLight = true;
						}
						else {
							m_HasLeftCaLight = false;
						}				
						break;
				}
			}
		}
		else {
			m_OnMouse = false;
		}

	}
```

**Comment by yttmwork** [comment]
@Kasugai0083 
確認しました。
きちんとチェックボックスを作って項目を洗い出しているのがとても良いです。
項目についてですが、Candleに関する処理のIssueと考えると
「プレイヤーにマウス情報を付与」はプレイヤーに関する処理追加になるので
別Issueにした方がいいと思います。

**Comment by Kasugai0083** [comment]
レビューありがとうございます

Issue の細分化については、今後意識します

GitHubの機能を見ていると他 issue のリンクや pull request なども紐づけることも可能なようなので、
次は新しい機能も利用して、細分化された他の項目との関係性を分かりやい 
Issue 造りに挑戦してみます

**Comment by Kasugai0083** [comment]
- Candleのステータスに依存して描画する

#3 にて解決
